backend:
  name: git-gateway
  branch: main

# Kam se ukládají obrázky nahrané v CMS
media_folder: "public"
public_folder: "/public"

# Zobrazení v editoru
locale: cs

collections:
  - name: "blog"
    label: "Články na blogu"
    label_singular: "Článek"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog.html"
    fields:
      - { label: "Nadpis článku", name: "title", widget: "string" }
      - { label: "Datum publikace", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Stručný popis", name: "description", widget: "text" }
      - { label: "Hlavní obrázek", name: "image", widget: "image", required: false }
      - { label: "Obsah článku", name: "body", widget: "markdown" }